# -*- coding: utf-8 -*-
"""text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFL6vAFKttkLv_T0o8Dxnmsxta3GDAUR
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read the image with the cv2 library
image = cv2.imread('/content/trafic_signal.jpg')

if image is None:
    print("Could not read the image")
    exit()

cv2_imshow(image)
cv2.waitKey(0)
cv2.destroyAllWindows()

#convert to greyscale
grey_scale = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2_imshow(grey_scale)
cv2.waitKey(0)
cv2.destroyAllWindows

#we apply a gaussian blur into the image
blurred_image = cv2.GaussianBlur(grey_scale, (5, 5), 0)
cv2_imshow(blurred_image)
cv2.waitKey(0)
cv2.destroyAllWindows

#edge detection by using canny in cv2
edges = cv2.Canny(blurred_image, 50, 150)

#orginal image
cv2_imshow(image)
cv2.waitKey(0)

#greyscale image
cv2_imshow(grey_scale)
cv2.waitKey(0)

#blurred image
cv2_imshow(blurred_image)
cv2.waitKey(0)

#edge detection
cv2_imshow(edges)
cv2.waitKey(0)
cv2.destroyAllWindows